export default {
  GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
  GET_MOVIES_FAIL: 'GET_MOVIES_FAIL',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIE_DETAILS_REQUEST: 'GET_MOVIE_DETAILS_REQUEST',
  GET_MOVIE_DETAILS_FAIL: 'GET_MOVIE_DETAILS_FAIL',
  GET_MOVIE_DETAILS_SUCCESS: 'GET_MOVIE_DETAILS_SUCCESS'
}
